### ISSUE TITLE
Internal Server Error bei Portfolio Liste

### ISSUE THREAD

**Issue by ch-web-design** [erdmannfreunde/contao-portfolio-bundle#11]
Hallo,

ih nutze Contao 4.13 und habe das Portfolio über den Manager installiert, ein Modul für die Portfolio Liste erstellt und im Artikel eingebunden. Wenn ich den Artikel nun bearbeiten möchte, kommt folgende Fehlermeldung:

`Attempted to load class "Utf8" from namespace "Patchwork". Did you forget a "use" statement for another namespace?`

Dieser Fehler scheint nur die Liste zu betreffen. Beim Leser tritt das nicht auf.

**Comment by denniserdmann** [comment]
Moin! 

Ich habe das Problem in der Version 4.3.1, die soeben erschienen ist, behoben.
