### ISSUE TITLE
Portfolioalias: Keine gültigen Alias-Zeichen

### ISSUE THREAD

**Issue by minstyle** [erdmannfreunde/contao-portfolio-bundle#12]
_Contao 4.13.5
PHP 7.4
erdmannfreunde/contao-portfolio-bundle 4.3.1_

Ich habe eine mehrsprachige Website. Bei jedem "Startpunkt" sind folgende "Gültige Alias-Zeichen" definiert:

![image](https://user-images.githubusercontent.com/2649562/176642668-8b7831fb-c9b9-479e-810c-3ac191dfd701.png)

D. h. bei der Erstellung von einem Alias dürfen beispielsweise auch keine Umlaute ö, ä, ü generiert werden.

Wenn ich nun in Contao ein neues Projekt unter "Portfolio" eintrage, dann werden die Contao-Einstellungen für "Gültige Alias-Zeichen" nicht berücksichtigt.

Beispiel:

![image](https://user-images.githubusercontent.com/2649562/176643459-4aeed94d-f363-41a3-90b3-cc7729e660a5.png)

Hier werden bspw. die Umlaute nicht automatisch in "ae", "oe" und "ue" etc. konvertiert.

falsch: `ich-bin-ein-test-mit-den-umlauten-äöü`
richtig: `ich-bin-ein-test-mit-den-umlauten-aeoeue`

**Comment by denniserdmann** [comment]
berücksichtigt in Version 4.4.0
