### ISSUE TITLE
Unterstützung von Mehrsprachigkeit

### ISSUE THREAD

**Issue by minstyle** [erdmannfreunde/contao-portfolio-bundle#14]
Aktuell unterstützt die Erweiterung leider keine Mehrsprachigkeit und bei einem einzelnen Portfolio-Eintrag kann kein "Hauptbeitrag" ausgewählt werden, wie dies besipielsweise im Core-Bundle "Nachrichten" der Fall ist.

![image](https://user-images.githubusercontent.com/2649562/176712115-de6aa501-5f49-4d1f-9e08-1e305299a7e4.png)

**Comment by denniserdmann** [comment]
added in [4.6.0](https://github.com/erdmannfreunde/contao-portfolio-bundle/releases/tag/4.6.0)
