### ISSUE TITLE
Unterstützung von Meta Tags

### ISSUE THREAD

**Issue by minstyle** [erdmannfreunde/contao-portfolio-bundle#15]
Aktuell können leider nicht pro Beitrag individuelle Meta Tags definiert werden, wie dies beispielsweise bei den "Nachrichten" der Fall ist.

![image](https://user-images.githubusercontent.com/2649562/176720190-363e8420-a405-45e9-a32e-bc4fc4d988c9.png)

Derzeit wird automatisch der gesamte Teasertext als `meta description` ausgegeben.

**Comment by denniserdmann** [comment]
berücksichtigt in Version 4.4.0

**Comment by minstyle** [comment]
@denniserdmann 

Vielen Dank für die Umsetzung 👌

![image](https://user-images.githubusercontent.com/2649562/178214748-22901e60-ccaa-4099-86a7-2f7d5a410f68.png)

Nach dem Update auf 4.4.0 sind mir hier noch zwei Dinge aufgefallen:

- Benennung der DCA `legend` "met_legend" in "Metadaten" könnte noch angepasst werden.
- Könnte hier noch die Auswahl für "Robots-Tag" hinzugefügt werden, wie ganz oben im Screenshot zu sehen?

**Comment by denniserdmann** [comment]
Danke für den Hinweis. Ich werde die Übersetzung bei Gelegenheit ergänzen. Der Robots Tag ist bei den News ab Contao 4.13 neu dazugekommen (Seitentitel und Beschreibung schon früher). Da ich die Erweiterung nicht auf 4.13 und neuer beschränken möchte, wird der Robots-Tag erstmal nicht kommen.
