### ISSUE TITLE
Legende „Unterüberschrift und Teaser“ falsch

### ISSUE THREAD

**Issue by minstyle** [erdmannfreunde/contao-portfolio-bundle#17]
Als `legend` ist in der Erweiterung "Unterüberschrift und Teaser" definiert. Allerdings fehlt das DCA-Feld `subheadline` und die Frontend-Ausgabe für die Unterüberschrift.

Screenshots:

![image](https://user-images.githubusercontent.com/2649562/179921924-87cdeb62-3858-4fde-b1a8-5dd58e4f84e5.png)

Bei dem Newsmodul von Contao ist die Unterüberschrift folgendermaßen eingebunden:

![image](https://user-images.githubusercontent.com/2649562/179922794-a451bb6d-4183-44e1-b118-3c8970fc81ac.png)

**Comment by denniserdmann** [comment]
Stimmt. Allerdings ist nur die Legende falsch. Es soll kein Feld Unterüberschrift geben. Wird in der nächsten Version angepasst.

**Comment by denniserdmann** [comment]
behoben in v4.4.2
