### ISSUE TITLE
404 bei ungültigem Alias

### ISSUE THREAD

**Issue by jorauch** [erdmannfreunde/contao-portfolio-bundle#25]
Wird eine Portfolio-Detail-Page mit unbekannten Alias aufgerufen, wird aktuelle die Meldung »Der Eintrag ALIAS existiert leider nicht.« und als Response Code 200 - OK zurückgegeben.
In diesem Fall wäre es sinnvoll der Response Code 404 - GONE auszugeben und auf die 404 Page weiterzuleiten. Damit wäre sichergestellt, dass eine nachträglich deaktivierte oder ändern des Alias´s auch dazu führt, dass die URL aus dem Suchindex z. B. von Googel entfernt wird.

(Ansonsten noch vielen Dank für die tolle Erweiterung.)

**Comment by rabauss** [comment]
Propably easy fix is to replace
https://github.com/erdmannfreunde/contao-portfolio-bundle/blob/418647ff824ebf0fc545e1d90496f39502e4e63f/src/Modules/ModulePortfolioReader.php#L101

with something like this:
```php
throw new PageNotFoundException('Page not found: ' . Environment::get('uri'));
```

see also: https://github.com/contao/contao/blob/4.13/news-bundle/src/Resources/contao/modules/ModuleNewsReader.php#L104

**Comment by denniserdmann** [comment]
fixed in [4.6.0](https://github.com/erdmannfreunde/contao-portfolio-bundle/releases/tag/4.6.0)
