### ISSUE TITLE
News nicht pflicht

### ISSUE THREAD

**Issue by katgirl** [erdmannfreunde/contao-portfolio-bundle#8]
PHP Warning:  Undefined array key "tl_news_archive" in /www/htdocs/var/cache/prod/contao/dca/tl_portfolio_category.php on line 16

Warning: Undefined array key "tl_news_archive" in /www/htdocs/var/cache/prod/contao/dca/tl_portfolio_category.php on line 16
PHP Warning:  Trying to access array offset on value of type null in /www/htdocs/var/cache/prod/contao/dca/tl_portfolio_category.php on line 16

Warning: Trying to access array offset on value of type null in /www/htdocs/var/cache/prod/contao/dca/tl_portfolio_category.php on line 16
PHP Warning:  Trying to access array offset on value of type null in /www/htdocs/var/cache/prod/contao/dca/tl_portfolio_category.php on line 16

Warning: Trying to access array offset on value of type null in /www/htdocs/var/cache/prod/contao/dca/tl_portfolio_category.php on line 16

**Comment by katgirl** [comment]
From https://docs.contao.org/dev/reference/dca/config/

"The label is used with page or file trees and typically includes reference to the language array."

This is a table tree, you can removing the line.

**Comment by denniserdmann** [comment]
fixed in 4.2.2
